### ISSUE TITLE
Finish Milestone 1 Deliverable

### ISSUE THREAD

**Issue by JonahRodriguez281** [powdr-ddc/powdr-ddc.github.io#1]
* [ ] Review entity classes
* [ ] Create Data Model implementation page with links to entity classes
* [ ] Review ERD
* [ ] Update exported ERD files (PNG & PDF)
